ch99/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    #Example: /bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name="add",),
    #Example: /bookmark/change/
    path('change/', views.BookmarkChangeLV.as_view(), name="change",),
    #Example: /bookmark/99/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update",),
    #Example: /bookmark/99/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete",),

]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from mysite.views import UserCreateView, UserCreateDoneTV
from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.index),
    path('create/', views.create),
    path('read/<id>/', views.read),
    path('update/<id>/', views.update),
    path('delete/', views.delete)
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

ch99/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

ch99/bookmark/views.py
from django.views.generic import ListView, DetailView
from .models import Bookmark
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

class BookmarkLV(ListView):
    model = Bookmark
class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

ch99/bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %} bookmark_change_list.html {% endblock %}

{% block header %}
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<h1>Bookmark Change - {{user}}</h1>
<br>

<table class="table table-bordered table-condensed table-striped">
    <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
            <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block extra-script %}{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %} bookmark_confirm_delete.html {% endblock %}

{% block header %}
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<h1>Bookmark Delete</h1>
<br>

<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
</form>
{% endblock %}

{% block extra-script %}{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %} home.html {% endblock %}

{% block header %}
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<center>
    <head>
        <title>Django Bookmark Detail</title>
    </head>

    <div id="content">
        <h1>{{ object.title }}</h1>

        <u1>
            <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
        </u1>
    </div>
</center>
{% endblock %}
{% block extra-script %}{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %} bookmark_form.html {% endblock %}

{% block header %}
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Bookmark</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<h1>Bookmark Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your bookmark.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

<form action="." method="post" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>

    <div class="form-group row">
        {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.url|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info"/>
        </div>
    </div>
</form>
{% endblock %}

{% block extra-script %}{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Django Bookmark List {% endblock %}

{% block header %}
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Bookmark</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<center>
<div id="content">
    <h1>Bookmark List</h1>
    <ul class="ml-auto mr-auto">
        {%for bookmark in object_list%}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
</center>
<div class="row justify-content-end">
    <div class="col-4">
        <a class="btn btn-light" href="{% url 'bookmark:add' %}">Add</a>
        <a class="btn btn-light" href="{% url 'bookmark:change' %}">Change</a>
    </div>
</div>

{% endblock %}

{% block extra-script %}{% endblock %}